version: '3'

services:
  postgres:
    build: postgres
    image: dawadk-postgres:1.0.0
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=$POSTGRES_DB_DATABASE
      - POSTGRES_USER=$POSTGRES_DB_USER
      - POSTGRES_PASSWORD=$POSTGRES_DB_PASSWORD
    volumes:
      - dawadk_db_volume:/var/lib/postgresql/data
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  replication-client:
    build: replication-client
    image: dawadk-replication-client:1.0.0
    restart: unless-stopped
    environment:
      - POSTGRES_DB=$POSTGRES_DB_DATABASE
      - POSTGRES_USER=$POSTGRES_DB_USER
      - POSTGRES_PASSWORD=$POSTGRES_DB_PASSWORD
      - REPLICATOR_SYNC_PERIOD=$REPLICATOR_SYNC_PERIOD
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  dawadk_db_volume: {}